default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        pass_filenames: true

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "--rcfile=.pylintrc",
          "--disable=C0114,C0115,C0116"
        ]