repos:
  - repo: local
    hooks:
      - id: lint
        name: ruff linter
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: true
        exclude: src/jfdi/extensions/ta_lib/.*

      - id: format
        name: ruff formatter
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true
