apiVersion: v1
kind: Namespace
metadata:
  name: trading
---
apiVersion: v1
kind: Namespace
metadata:
  name: backtesting
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator 
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant 
