apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jfdi.fullname" . }}
  labels:
    {{- include "jfdi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "jfdi.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jfdi.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.container.workingDir }}
          command: {{- toYaml .Values.container.command | nindent 12 }}
          args: {{- toYaml .Values.container.args | nindent 12 }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- range .Values.secrets }}
              {{- $secretName := .name }}
              {{- range .keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . }}
              {{- end }}
            {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
